name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend  # 👈 ISSO AQUI

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build
        run: npm run build